---
- name: Add server {{ id }} to monitoring
  local_action:
    module: zabbix_host
    server_url: "{{ zabbix_server_url }}"
    login_user: "{{ zabbix_server_login }}"
    login_password: "{{ zabbix_server_password }}"
#    host_name: "{{ inventory_hostname }}"
    host_name: "{{ server_name }}"
    host_groups:
      - "Frigate-proxy"
      - "Linux servers"
    link_templates:
      - "Template OS Linux"
    status: enabled
    state: present
    inventory_mode: automatic
    inventory_zabbix:
      tag: "id: {{ id }}"
    interfaces:
      - type: 1
        main: 1
        useip: 1
        ip: "{{ ansible_ssh_host }}"
        dns: ""
        port: "{{ zabbix_agent_port }}"
    macros:
      - macro: "SSH_PORT"
        value: "{{ ansible_ssh_port }}"
    tags:
      - tag: "id"
        value: "{{ id }}"
    tls_psk_identity: "{{ zabbix_agent_psk_identity }}"
    tls_connect: 2
    tls_accept: 2
    tls_psk: "{{ zabbix_agent_psk }}"
    validate_certs: no
  become: no

